In [1]:
import numpy as np

In [2]:
def char_to_bin (s):
    mp =  dict()
    mp['f'] = "0000"
    mp['g'] = "0001" 
    mp['h'] = "0010" 
    mp['i']       = "0011" 
    mp['j'] = "0100" 
    mp['k'] = "0101" 
    mp['l'] = "0110" 
    mp['m'] = "0111" 
    mp['n'] = "1000" 
    mp['o'] = "1001" 
    mp['p'] = "1010" 
    mp['q'] = "1011" 
    mp['r'] = "1100" 
    mp['s'] = "1101" 
    mp['t'] = "1110" 
    mp['u'] = "1111" 
    binary = ""
    for i in range (len(s)):
        binary = binary + mp[s[i]]
    return binary; 
    
def bin_to_char (s,size_out):
    mp =dict()
    mp["0000"] = "f"; 
    mp["0001"] = "g"; 
    mp["0010"] = "h"; 
    mp["0011"] = "i"; 
    mp["0100"] = "j"; 
    mp["0101"] = "k"; 
    mp["0110"] = "l"; 
    mp["0111"] = "m"; 
    mp["1000"] = "n"; 
    mp["1001"] = "o"; 
    mp["1010"] = "p"; 
    mp["1011"] = "q"; 
    mp["1100"] = "r"; 
    mp["1101"] = "s"; 
    mp["1110"] = "t"; 
    mp["1111"] = "u"; 
    char = "" 
    for i in range (0,size_out):
        ch=s[i*4:4*(i+1)]
        char=char+mp[ch];

    return char

def bin_to_dec(s):
    ans = 0
    for i in range(0,len(s)):
        if(s[len(s)-i-1]=='1'):
            ans=ans+pow(2,i)
        
    return ans;

In [444]:
from pyfinite import ffield
import itertools

In [445]:
F = ffield.FField(7)

In [446]:
all_bytes = list(itertools.product([0, 1], repeat=8))
all_bytes = list(convertlistToStr(i) for i in all_bytes);#fiter

In [574]:
all_bytes_text = []
for ind in range(0,128):
    i = all_bytes[ind]
    temp=bin_to_char(i,2)
    all_bytes_text.append(temp)
    
print(all_bytes_text)

['ff', 'fg', 'fh', 'fi', 'fj', 'fk', 'fl', 'fm', 'fn', 'fo', 'fp', 'fq', 'fr', 'fs', 'ft', 'fu', 'gf', 'gg', 'gh', 'gi', 'gj', 'gk', 'gl', 'gm', 'gn', 'go', 'gp', 'gq', 'gr', 'gs', 'gt', 'gu', 'hf', 'hg', 'hh', 'hi', 'hj', 'hk', 'hl', 'hm', 'hn', 'ho', 'hp', 'hq', 'hr', 'hs', 'ht', 'hu', 'if', 'ig', 'ih', 'ii', 'ij', 'ik', 'il', 'im', 'in', 'io', 'ip', 'iq', 'ir', 'is', 'it', 'iu', 'jf', 'jg', 'jh', 'ji', 'jj', 'jk', 'jl', 'jm', 'jn', 'jo', 'jp', 'jq', 'jr', 'js', 'jt', 'ju', 'kf', 'kg', 'kh', 'ki', 'kj', 'kk', 'kl', 'km', 'kn', 'ko', 'kp', 'kq', 'kr', 'ks', 'kt', 'ku', 'lf', 'lg', 'lh', 'li', 'lj', 'lk', 'll', 'lm', 'ln', 'lo', 'lp', 'lq', 'lr', 'ls', 'lt', 'lu', 'mf', 'mg', 'mh', 'mi', 'mj', 'mk', 'ml', 'mm', 'mn', 'mo', 'mp', 'mq', 'mr', 'ms', 'mt', 'mu']


In [448]:
rand_string = 'fjhsijgkoshufp'
all_bytes_text_1=[]
for i in all_bytes_text:
    all_bytes_text_1.append(i+rand_string)
    


In [449]:
for i in range(0,256):
    print(F.ShowPolynomial(i))

0
1
x^1
x^1 + 1
x^2
x^2 + 1
x^2 + x^1
x^2 + x^1 + 1
x^3
x^3 + 1
x^3 + x^1
x^3 + x^1 + 1
x^3 + x^2
x^3 + x^2 + 1
x^3 + x^2 + x^1
x^3 + x^2 + x^1 + 1
x^4
x^4 + 1
x^4 + x^1
x^4 + x^1 + 1
x^4 + x^2
x^4 + x^2 + 1
x^4 + x^2 + x^1
x^4 + x^2 + x^1 + 1
x^4 + x^3
x^4 + x^3 + 1
x^4 + x^3 + x^1
x^4 + x^3 + x^1 + 1
x^4 + x^3 + x^2
x^4 + x^3 + x^2 + 1
x^4 + x^3 + x^2 + x^1
x^4 + x^3 + x^2 + x^1 + 1
x^5
x^5 + 1
x^5 + x^1
x^5 + x^1 + 1
x^5 + x^2
x^5 + x^2 + 1
x^5 + x^2 + x^1
x^5 + x^2 + x^1 + 1
x^5 + x^3
x^5 + x^3 + 1
x^5 + x^3 + x^1
x^5 + x^3 + x^1 + 1
x^5 + x^3 + x^2
x^5 + x^3 + x^2 + 1
x^5 + x^3 + x^2 + x^1
x^5 + x^3 + x^2 + x^1 + 1
x^5 + x^4
x^5 + x^4 + 1
x^5 + x^4 + x^1
x^5 + x^4 + x^1 + 1
x^5 + x^4 + x^2
x^5 + x^4 + x^2 + 1
x^5 + x^4 + x^2 + x^1
x^5 + x^4 + x^2 + x^1 + 1
x^5 + x^4 + x^3
x^5 + x^4 + x^3 + 1
x^5 + x^4 + x^3 + x^1
x^5 + x^4 + x^3 + x^1 + 1
x^5 + x^4 + x^3 + x^2
x^5 + x^4 + x^3 + x^2 + 1
x^5 + x^4 + x^3 + x^2 + x^1
x^5 + x^4 + x^3 + x^2 + x^1 + 1
x^6
x^6 + 1
x^6 + x^1
x^6 + x^1 + 1


In [ ]:
################################
#FINDING A matrix and E vector ######
################################

In [450]:
print(bin_to_dec(char_to_bin('kh')))
print(bin_to_dec(char_to_bin('km')))

def field_pow(num,p):
    ans=1
    for i in range(0,p):
        ans=F.Multiply(ans,num)
        
    return ans

82
87


In [451]:
tuples = []
x=1
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==82):
            tuples.append((a88,e8))

In [452]:
print(tuples)

[(2, 23), (2, 103), (3, 47), (3, 79), (5, 51), (5, 75), (7, 42), (7, 84), (9, 20), (9, 106), (10, 15), (10, 111), (13, 32), (13, 94), (14, 46), (14, 80), (15, 35), (15, 91), (17, 7), (17, 119), (18, 18), (18, 108), (19, 26), (19, 100), (22, 54), (22, 72), (24, 33), (24, 93), (29, 53), (29, 73), (30, 1), (30, 125), (32, 38), (32, 88), (34, 59), (34, 67), (35, 37), (35, 89), (36, 43), (36, 83), (38, 45), (38, 81), (41, 48), (41, 78), (42, 25), (42, 101), (43, 21), (43, 105), (45, 13), (45, 113), (48, 57), (48, 69), (49, 49), (49, 77), (51, 27), (51, 99), (52, 2), (52, 124), (54, 61), (54, 65), (55, 17), (55, 109), (56, 52), (56, 74), (57, 31), (57, 95), (59, 39), (59, 87), (61, 34), (61, 92), (62, 44), (62, 82), (64, 24), (64, 102), (65, 14), (65, 112), (67, 36), (67, 90), (68, 58), (68, 68), (75, 12), (75, 114), (78, 3), (78, 123), (81, 4), (81, 122), (83, 30), (83, 96), (90, 63), (91, 16), (91, 110), (92, 41), (92, 85), (93, 60), (93, 66), (94, 29), (94, 97), (103, 50), (103, 76), (108

In [453]:
tuples2 = []
x=2
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==87):
            tuples2.append((a88,e8))

tuples3 = list(set(tuples) & set(tuples2))

In [454]:
print(bin_to_dec(char_to_bin('fk')))

5


In [455]:
print(tuples3)

[(91, 16), (103, 50), (54, 61)]


In [456]:
tuples4 = []
x=3
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==5):
            tuples4.append((a88,e8))

tuples5 = list(set(tuples3) & set(tuples4))
print(tuples5)

[(91, 16), (103, 50), (54, 61)]


In [457]:
A_matrix = [0, 0, 0, 0, 0, 0, 0, 0, 0]
A_matrix[8] = tuples5

In [458]:
print(bin_to_dec(char_to_bin('ko')))
print(bin_to_dec(char_to_bin('hg')))
print(bin_to_dec(char_to_bin('kl')))

89
33
86


In [459]:
tuples = []
x=1
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==89):
            tuples.append((a88,e8))
            
tuples2 = []
x=2
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==33):
            tuples2.append((a88,e8))
            
x=3
tuples3 = []
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==86):
            tuples3.append((a88,e8))

tuples4 = list(set(tuples) & set(tuples2))
tuples5 = list(set(tuples3) & set(tuples4))

In [460]:
print(tuples5)

[(14, 66), (37, 77), (96, 111)]


In [461]:
A_matrix[7] = tuples5

In [462]:
print(bin_to_dec(char_to_bin('lj')))
print(bin_to_dec(char_to_bin('kt')))
print(bin_to_dec(char_to_bin('ip')))

100
94
58


In [463]:
tuples = []
x=1
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==100):
            tuples.append((a88,e8))
            
tuples2 = []
x=2
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==94):
            tuples2.append((a88,e8))
            
x=3
tuples3 = []
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==58):
            tuples3.append((a88,e8))

tuples4 = list(set(tuples) & set(tuples2))
tuples5 = list(set(tuples3) & set(tuples4))

print(tuples5)
A_matrix[6] = tuples5

[(87, 38), (93, 2), (121, 87)]


In [464]:
print(bin_to_dec(char_to_bin('in')))
print(bin_to_dec(char_to_bin('lg')))
print(bin_to_dec(char_to_bin('ji')))

56
97
67


In [465]:
tuples = []
x=1
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==56):
            tuples.append((a88,e8))
            
tuples2 = []
x=2
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==97):
            tuples2.append((a88,e8))
            
x=3
tuples3 = []
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==67):
            tuples3.append((a88,e8))

tuples4 = list(set(tuples) & set(tuples2))
tuples5 = list(set(tuples3) & set(tuples4))

print(tuples5)
A_matrix[5] = tuples5

[(59, 93), (39, 45), (16, 116)]


In [466]:
print(bin_to_dec(char_to_bin('fi')))
print(bin_to_dec(char_to_bin('fj')))
print(bin_to_dec(char_to_bin('kr')))

3
4
92


In [467]:
tuples = []
x=1
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==3):
            tuples.append((a88,e8))
            
tuples2 = []
x=2
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==4):
            tuples2.append((a88,e8))
            
x=3
tuples3 = []
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==92):
            tuples3.append((a88,e8))

tuples4 = list(set(tuples) & set(tuples2))
tuples5 = list(set(tuples3) & set(tuples4))

print(tuples5)
A_matrix[4] = tuples5

[(60, 98), (22, 84), (50, 72)]


In [468]:
print(bin_to_dec(char_to_bin('it')))
print(bin_to_dec(char_to_bin('fm')))
print(bin_to_dec(char_to_bin('io')))

62
7
57


In [469]:
tuples = []
x=1
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==62):
            tuples.append((a88,e8))
            
tuples2 = []
x=2
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==7):
            tuples2.append((a88,e8))
            
x=3
tuples3 = []
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==57):
            tuples3.append((a88,e8))

tuples4 = list(set(tuples) & set(tuples2))
tuples5 = list(set(tuples3) & set(tuples4))

print(tuples5)
A_matrix[3] = tuples5

[(40, 38), (6, 2), (89, 87)]


In [470]:
print(bin_to_dec(char_to_bin('kh')))
print(bin_to_dec(char_to_bin('fo')))
print(bin_to_dec(char_to_bin('mq')))

82
9
123


In [471]:
tuples = []
x=1
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==82):
            tuples.append((a88,e8))
            
tuples2 = []
x=2
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==9):
            tuples2.append((a88,e8))
            
x=3
tuples3 = []
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==123):
            tuples3.append((a88,e8))

tuples4 = list(set(tuples) & set(tuples2))
tuples5 = list(set(tuples3) & set(tuples4))

print(tuples5)
A_matrix[2] = tuples5

[(2, 103), (51, 99), (56, 52)]


In [472]:
print(bin_to_dec(char_to_bin('fo')))
print(bin_to_dec(char_to_bin('gj')))
print(bin_to_dec(char_to_bin('hq')))

9
20
43


In [473]:
tuples = []
x=1
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==9):
            tuples.append((a88,e8))
            
tuples2 = []
x=2
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==20):
            tuples2.append((a88,e8))
            
x=3
tuples3 = []
for a88 in range(0,128):
    for e8 in range(1,127):
        a = F.Multiply(a88,field_pow(x,e8))
        b = F.Multiply(a88,field_pow(a,e8))
        c = field_pow(b,e8)
        if(c==43):
            tuples3.append((a88,e8))

tuples4 = list(set(tuples) & set(tuples2))
tuples5 = list(set(tuples3) & set(tuples4))

print(tuples5)
A_matrix[1] = tuples5

[(100, 85), (87, 78), (25, 91)]


In [474]:
for i in A_matrix:
    print(i)

0
[(100, 85), (87, 78), (25, 91)]
[(2, 103), (51, 99), (56, 52)]
[(40, 38), (6, 2), (89, 87)]
[(60, 98), (22, 84), (50, 72)]
[(59, 93), (39, 45), (16, 116)]
[(87, 38), (93, 2), (121, 87)]
[(14, 66), (37, 77), (96, 111)]
[(91, 16), (103, 50), (54, 61)]


In [475]:
print(bin_to_dec(char_to_bin('ki')))
print(bin_to_dec(char_to_bin('ju')))
print(bin_to_dec(char_to_bin('jg')))

83
79
65


In [476]:
x=1

tuples = []
for i in A_matrix[8]:
    for j in A_matrix[7]:
        for A87 in range(0,128):
            A88 = i[0]
            e8 = i[1]
            A77 = j[0]
            e7 = j[1]
            t1 = F.Multiply(A77,field_pow(x,e7))
            t1 = field_pow(t1,e7)
            t1 = F.Multiply(A87,t1)
            t2 = F.Multiply(A87,field_pow(x,e7))
            t2 = field_pow(t2,e8)
            t2 = F.Multiply(A88,t2)
            t = F.Add(t1,t2)
            t = field_pow(t,e8)
            if(t==83):
                tuples.append((i[0],i[1],j[0],j[1],A87))
                
x=2

tuples2 = []
for i in A_matrix[8]:
    for j in A_matrix[7]:
        for A87 in range(0,128):
            A88 = i[0]
            e8 = i[1]
            A77 = j[0]
            e7 = j[1]
            t1 = F.Multiply(A77,field_pow(x,e7))
            t1 = field_pow(t1,e7)
            t1 = F.Multiply(A87,t1)
            t2 = F.Multiply(A87,field_pow(x,e7))
            t2 = field_pow(t2,e8)
            t2 = F.Multiply(A88,t2)
            t = F.Add(t1,t2)
            t = field_pow(t,e8)
            if(t==79):
                tuples2.append((i[0],i[1],j[0],j[1],A87))

x=3

tuples3 = []
for i in A_matrix[8]:
    for j in A_matrix[7]:
        for A87 in range(0,128):
            A88 = i[0]
            e8 = i[1]
            A77 = j[0]
            e7 = j[1]
            t1 = F.Multiply(A77,field_pow(x,e7))
            t1 = field_pow(t1,e7)
            t1 = F.Multiply(A87,t1)
            t2 = F.Multiply(A87,field_pow(x,e7))
            t2 = field_pow(t2,e8)
            t2 = F.Multiply(A88,t2)
            t = F.Add(t1,t2)
            t = field_pow(t,e8)
            if(t==65):
                tuples3.append((i[0],i[1],j[0],j[1],A87))

tuples4 = list(set(tuples) & set(tuples2))
tuples5 = list(set(tuples3) & set(tuples4))

print(tuples5)

[(103, 50, 14, 66, 37)]


In [477]:
A_map = np.zeros((9,9), dtype=int)
A_map[8][8] = 103
A_map[8][7] = 37
A_map[7][7] = 14

E_map = np.zeros(9, dtype=int)
E_map[8] = 50
E_map[7] = 66
print(type(E_map[7]))

print(bin_to_dec(char_to_bin('ll')))
print(bin_to_dec(char_to_bin('hs')))
print(bin_to_dec(char_to_bin('il')))
print(bin_to_dec(char_to_bin('lj')))

<class 'numpy.int64'>
102
45
54
100


In [478]:
string = []
string.append(('', ''))
string.append(('fokqiolmiuijgffs', 'gjggjrglkmhhmuhq', 'hqfhhufijmjufsfg'))
string.append(('ffkhlojphmgjkhil', 'fffogtirilkjinku', 'ffmqkqfkiumkmhiq'))
string.append(('ffffitkfgrlritmq', 'fffffmighnmlfpis', 'ffffiohtkmljgnlu'))
string.append(('fffffffijsjkfhmf', 'fffffffjgtmrljfi', 'ffffffkrhtfohhfq'))
string.append(('ffffffffingjgrhs', 'fffffffflgkogglk', 'ffffffffjilklhgq'))
string.append(('ffffffffffljllil', 'ffffffffffkthslj', 'ffffffffffiphthi'))
string.append(('ffffffffffffkoki', 'ffffffffffffhgju', 'ffffffffffffkljg'))
string.append(('ffffffffffffffkh', 'ffffffffffffffkm', 'fffffffffffffffk'))

bin_to_dec(char_to_bin('gj'))

# val= []
# val.append((0,0))
# val.append((,bin_to_dec(char_to_bin('ll'))))
# val[5][0] = bin_to_dec(char_to_bin('ll'))
# val[5][1] = bin_to_dec(char_to_bin('ll'))
# val[4][0] = bin_to_dec(char_to_bin('ll'))
# val[4][1] = bin_to_dec(char_to_bin('ll'))
# val[3][0] = bin_to_dec(char_to_bin('ll'))
# val[3][1] = bin_to_dec(char_to_bin('ll'))
# val[2][0] = bin_to_dec(char_to_bin('ll'))
# val[2][1] = bin_to_dec(char_to_bin('ll'))
# val[1][0] = bin_to_dec(char_to_bin('ll'))
# val[1][1] = bin_to_dec(char_to_bin('ll'))

20

In [479]:
#diagonal and just below

for ind in range(1,8):
    i=8-ind
    outval1 = bin_to_dec(char_to_bin(string[i][0][2*(i):2*(i+1)]))
    outval2 = bin_to_dec(char_to_bin(string[i][1][2*(i):2*(i+1)]))
    outval3 = bin_to_dec(char_to_bin(string[i][2][2*(i):2*(i+1)]))
    x=1
    tuples = []
    for tups in A_matrix[i]:
        for aipi in range(0,128):
            aii = tups[0]
            ei = tups[1]
            t1 = F.Multiply(aii,field_pow(x,ei))
            t1 = field_pow(t1,ei)
            t1 = F.Multiply(aipi,t1)
            t2 = F.Multiply(aipi,field_pow(x,ei))
            t2 = field_pow(t2,E_map[i+1])
            t2 = F.Multiply(A_map[i+1][i+1],t2)
            t = F.Add(t1,t2)
            t = field_pow(t,E_map[i+1])
            if(t==outval1):
                tuples.append((tups[0],tups[1],aipi))
                
    x=2
    tuples2 = []
    for tups in A_matrix[i]:
        for aipi in range(0,128):
            aii = tups[0]
            ei = tups[1]
            t1 = F.Multiply(aii,field_pow(x,ei))
            t1 = field_pow(t1,ei)
            t1 = F.Multiply(aipi,t1)
            t2 = F.Multiply(aipi,field_pow(x,ei))
            t2 = field_pow(t2,E_map[i+1])
            t2 = F.Multiply(A_map[i+1][i+1],t2)
            t = F.Add(t1,t2)
            t = field_pow(t,E_map[i+1])
            if(t==outval2):
                tuples2.append((tups[0],tups[1],aipi))
                
    x=3
    tuples3 = []
    for tups in A_matrix[i]:
        for aipi in range(0,128):
            aii = tups[0]
            ei = tups[1]
            t1 = F.Multiply(aii,field_pow(x,ei))
            t1 = field_pow(t1,ei)
            t1 = F.Multiply(aipi,t1)
            t2 = F.Multiply(aipi,field_pow(x,ei))
            t2 = field_pow(t2,E_map[i+1])
            t2 = F.Multiply(A_map[i+1][i+1],t2)
            t = F.Add(t1,t2)
            t = field_pow(t,E_map[i+1])
            if(t==outval3):
                tuples3.append((tups[0],tups[1],aipi))
                
    tuples4 = list(set(tuples) & set(tuples2))
    tuples5 = list(set(tuples4) & set(tuples3))
    print(tuples5)
    A_map[i][i]=tuples5[0][0]
    A_map[i+1][i]=tuples5[0][2]
    E_map[i]=tuples5[0][1]

[(14, 66, 37)]
[(87, 38, 44)]
[(16, 116, 92)]
[(50, 72, 10)]
[(40, 38, 77)]
[(56, 52, 121)]
[(100, 85, 122)]


In [480]:
print(A_map,E_map)

[[  0   0   0   0   0   0   0   0   0]
 [  0 100   0   0   0   0   0   0   0]
 [  0 122  56   0   0   0   0   0   0]
 [  0   0 121  40   0   0   0   0   0]
 [  0   0   0  77  50   0   0   0   0]
 [  0   0   0   0  10  16   0   0   0]
 [  0   0   0   0   0  92  87   0   0]
 [  0   0   0   0   0   0  44  14   0]
 [  0   0   0   0   0   0   0  37 103]] [  0  85  52  38  72 116  38  66  50]


In [481]:
for ind in range(1,7):
    j=7
    i=7-ind
    outval = bin_to_dec(char_to_bin(string[i][1][2*(i+1):2*(i+2)]))
    x=2
    tuples = []
    for aip2i in range(0,128):
        t1 = F.Multiply(A_map[i][i],field_pow(x,E_map[i]))
        t1 = field_pow(t1,E_map[i])
        t1 = F.Multiply(t1,aip2i)
        
        t2 = F.Multiply(A_map[i+1][i],field_pow(x,E_map[i]))
        t2 = field_pow(t2,E_map[i+1])
        t2 = F.Multiply(t2,A_map[i+2][i+1])
        
        t3 = F.Multiply(aip2i,field_pow(x,E_map[i]))
        t3 = field_pow(t3,E_map[i+2])
        t3 = F.Multiply(t3,A_map[i+2][i+2])
        
        t1 = F.Add(t1,t2)
        t = F.Add(t1,t3)
        t = field_pow(t,E_map[i+2])
        if(t==outval):
            tuples.append(aip2i)
            

            
    outval2 = bin_to_dec(char_to_bin(string[i][2][2*(i+1):2*(i+2)]))
    x=3
    tuples2 = []
    for aip2i in range(0,128):
        t1 = F.Multiply(A_map[i][i],field_pow(x,E_map[i]))
        t1 = field_pow(t1,E_map[i])
        t1 = F.Multiply(t1,aip2i)
        
        t2 = F.Multiply(A_map[i+1][i],field_pow(x,E_map[i]))
        t2 = field_pow(t2,E_map[i+1])
        t2 = F.Multiply(t2,A_map[i+2][i+1])
        
        t3 = F.Multiply(aip2i,field_pow(x,E_map[i]))
        t3 = field_pow(t3,E_map[i+2])
        t3 = F.Multiply(t3,A_map[i+2][i+2])
        
        t1 = F.Add(t1,t2)
        t = F.Add(t1,t3)
        t = field_pow(t,E_map[i+2])
        if(t==outval2):
            tuples2.append(aip2i)
    
    print(tuples,tuples2)
    tuples3 = list(set(tuples) & set(tuples2))
    print(tuples3)
    A_map[i+2][i] = tuples3[0]

[17] [17, 20, 40]
[17]
[104] [26, 104]
[104]
[116] [34, 81, 116]
[116]
[78] [78]
[78]
[1, 79, 97] [97]
[97]
[6] [6, 7, 68]
[6]


In [482]:
print(A_map)

[[  0   0   0   0   0   0   0   0   0]
 [  0 100   0   0   0   0   0   0   0]
 [  0 122  56   0   0   0   0   0   0]
 [  0   6 121  40   0   0   0   0   0]
 [  0   0  97  77  50   0   0   0   0]
 [  0   0   0  78  10  16   0   0   0]
 [  0   0   0   0 116  92  87   0   0]
 [  0   0   0   0   0 104  44  14   0]
 [  0   0   0   0   0   0  17  37 103]]


In [483]:
for ind in range(1,6):
    j=7
    i=6-ind
    outval = bin_to_dec(char_to_bin(string[i][1][2*(i+2):2*(i+3)]))
    x=2
    tuples = []
    for aip3i in range(0,128):
        t1 = F.Multiply(A_map[i][i],field_pow(x,E_map[i]))
        t1 = field_pow(t1,E_map[i])
        t1 = F.Multiply(t1,aip3i)
        
        t2 = F.Multiply(A_map[i+1][i],field_pow(x,E_map[i]))
        t2 = field_pow(t2,E_map[i+1])
        t2 = F.Multiply(t2,A_map[i+3][i+1])
        
        t3 = F.Multiply(A_map[i+2][i],field_pow(x,E_map[i]))
        t3 = field_pow(t3,E_map[i+2])
        t3 = F.Multiply(t3,A_map[i+3][i+2])
        
        t4 = F.Multiply(aip3i,field_pow(x,E_map[i]))
        t4 = field_pow(t4,E_map[i+3])
        t4 = F.Multiply(t4,A_map[i+3][i+3])
        
        ta = F.Add(t1,t2)
        tb = F.Add(ta,t3)
        tc = F.Add(tb,t4)
        t = field_pow(tc,E_map[i+3])
        if(t==outval):
            tuples.append(aip3i)
            
    outval2 = bin_to_dec(char_to_bin(string[i][2][2*(i+2):2*(i+3)]))
    x=3
    tuples2 = []
    for aip3i in range(0,128):
        t1 = F.Multiply(A_map[i][i],field_pow(x,E_map[i]))
        t1 = field_pow(t1,E_map[i])
        t1 = F.Multiply(t1,aip3i)
        
        t2 = F.Multiply(A_map[i+1][i],field_pow(x,E_map[i]))
        t2 = field_pow(t2,E_map[i+1])
        t2 = F.Multiply(t2,A_map[i+3][i+1])
        
        t3 = F.Multiply(A_map[i+2][i],field_pow(x,E_map[i]))
        t3 = field_pow(t3,E_map[i+2])
        t3 = F.Multiply(t3,A_map[i+3][i+2])
        
        t4 = F.Multiply(aip3i,field_pow(x,E_map[i]))
        t4 = field_pow(t4,E_map[i+3])
        t4 = F.Multiply(t4,A_map[i+3][i+3])
        
        ta = F.Add(t1,t2)
        tb = F.Add(ta,t3)
        tc = F.Add(tb,t4)
        t = field_pow(tc,E_map[i+3])
        if(t==outval2):
            tuples2.append(aip3i)
            
    tuples3 = list(set(tuples) & set(tuples2))
    print(tuples3)
    A_map[i+3][i] = tuples3[0]

[113]
[92]
[114]
[14]
[10]


In [484]:
print(A_map)

[[  0   0   0   0   0   0   0   0   0]
 [  0 100   0   0   0   0   0   0   0]
 [  0 122  56   0   0   0   0   0   0]
 [  0   6 121  40   0   0   0   0   0]
 [  0  10  97  77  50   0   0   0   0]
 [  0   0  14  78  10  16   0   0   0]
 [  0   0   0 114 116  92  87   0   0]
 [  0   0   0   0  92 104  44  14   0]
 [  0   0   0   0   0 113  17  37 103]]


In [485]:
for ind in range(1,5):
    j=7
    i=5-ind
    outval = bin_to_dec(char_to_bin(string[i][1][2*(i+3):2*(i+4)]))
    x=2
    tuples = []
    for aip4i in range(0,128):
        t1 = F.Multiply(A_map[i][i],field_pow(x,E_map[i]))
        t1 = field_pow(t1,E_map[i])
        t1 = F.Multiply(t1,aip4i)
        
        t2 = F.Multiply(A_map[i+1][i],field_pow(x,E_map[i]))
        t2 = field_pow(t2,E_map[i+1])
        t2 = F.Multiply(t2,A_map[i+4][i+1])
        
        t3 = F.Multiply(A_map[i+2][i],field_pow(x,E_map[i]))
        t3 = field_pow(t3,E_map[i+2])
        t3 = F.Multiply(t3,A_map[i+4][i+2])
        
        t4 = F.Multiply(A_map[i+3][i],field_pow(x,E_map[i]))
        t4 = field_pow(t4,E_map[i+3])
        t4 = F.Multiply(t4,A_map[i+4][i+3])
        
        t5 = F.Multiply(aip4i,field_pow(x,E_map[i]))
        t5 = field_pow(t5,E_map[i+4])
        t5 = F.Multiply(t5,A_map[i+4][i+4])
        
        t1 = F.Add(t1,t2)
        t2 = F.Add(t1,t3)
        t = F.Add(t2,t4)
        t = F.Add(t,t5)
        t = field_pow(t,E_map[i+4])
        if(t==outval):
            tuples.append(aip4i)
            
    outval2 = bin_to_dec(char_to_bin(string[i][2][2*(i+3):2*(i+4)]))
    x=3
    tuples2 = []
    for aip4i in range(0,128):
        t1 = F.Multiply(A_map[i][i],field_pow(x,E_map[i]))
        t1 = field_pow(t1,E_map[i])
        t1 = F.Multiply(t1,aip4i)
        
        t2 = F.Multiply(A_map[i+1][i],field_pow(x,E_map[i]))
        t2 = field_pow(t2,E_map[i+1])
        t2 = F.Multiply(t2,A_map[i+4][i+1])
        
        t3 = F.Multiply(A_map[i+2][i],field_pow(x,E_map[i]))
        t3 = field_pow(t3,E_map[i+2])
        t3 = F.Multiply(t3,A_map[i+4][i+2])
        
        t4 = F.Multiply(A_map[i+3][i],field_pow(x,E_map[i]))
        t4 = field_pow(t4,E_map[i+3])
        t4 = F.Multiply(t4,A_map[i+4][i+3])
        
        t5 = F.Multiply(aip4i,field_pow(x,E_map[i]))
        t5 = field_pow(t5,E_map[i+4])
        t5 = F.Multiply(t5,A_map[i+4][i+4])
        
        t1 = F.Add(t1,t2)
        t2 = F.Add(t1,t3)
        t = F.Add(t2,t4)
        t = F.Add(t,t5)
        t = field_pow(t,E_map[i+4])
        if(t==outval2):
            tuples2.append(aip4i)
            
    tuples3 = list(set(tuples) & set(tuples2))
    print(tuples3)
    A_map[i+4][i] = tuples3[0]

[58]
[98]
[76]
[58]


In [486]:
print(A_map)

[[  0   0   0   0   0   0   0   0   0]
 [  0 100   0   0   0   0   0   0   0]
 [  0 122  56   0   0   0   0   0   0]
 [  0   6 121  40   0   0   0   0   0]
 [  0  10  97  77  50   0   0   0   0]
 [  0  58  14  78  10  16   0   0   0]
 [  0   0  76 114 116  92  87   0   0]
 [  0   0   0  98  92 104  44  14   0]
 [  0   0   0   0  58 113  17  37 103]]


In [487]:
for ind in range(1,4):
    j=7
    i=4-ind
    outval = bin_to_dec(char_to_bin(string[i][1][2*(i+4):2*(i+5)]))
    x=2
    tuples = []
    for aip5i in range(0,128):
        t1 = F.Multiply(A_map[i][i],field_pow(x,E_map[i]))
        t1 = field_pow(t1,E_map[i])
        t1 = F.Multiply(t1,aip5i)
        
        t2 = F.Multiply(A_map[i+1][i],field_pow(x,E_map[i]))
        t2 = field_pow(t2,E_map[i+1])
        t2 = F.Multiply(t2,A_map[i+5][i+1])
        
        t3 = F.Multiply(A_map[i+2][i],field_pow(x,E_map[i]))
        t3 = field_pow(t3,E_map[i+2])
        t3 = F.Multiply(t3,A_map[i+5][i+2])
        
        t4 = F.Multiply(A_map[i+3][i],field_pow(x,E_map[i]))
        t4 = field_pow(t4,E_map[i+3])
        t4 = F.Multiply(t4,A_map[i+5][i+3])
        
        t5 = F.Multiply(A_map[i+4][i],field_pow(x,E_map[i]))
        t5 = field_pow(t5,E_map[i+4])
        t5 = F.Multiply(t5,A_map[i+5][i+4])
        
        t6 = F.Multiply(aip5i,field_pow(x,E_map[i]))
        t6 = field_pow(t6,E_map[i+5])
        t6 = F.Multiply(t6,A_map[i+5][i+5])
        
        t = F.Add(t1,t2)
        t = F.Add(t,t3)
        t = F.Add(t,t4)
        t = F.Add(t,t5)
        t = F.Add(t,t6)
        
        t = field_pow(t,E_map[i+5])
        if(t==outval):
            tuples.append(aip5i)
            
    outval2 = bin_to_dec(char_to_bin(string[i][2][2*(i+4):2*(i+5)]))
    x=3
    tuples2 = []
    for aip5i in range(0,128):
        t1 = F.Multiply(A_map[i][i],field_pow(x,E_map[i]))
        t1 = field_pow(t1,E_map[i])
        t1 = F.Multiply(t1,aip5i)
        
        t2 = F.Multiply(A_map[i+1][i],field_pow(x,E_map[i]))
        t2 = field_pow(t2,E_map[i+1])
        t2 = F.Multiply(t2,A_map[i+5][i+1])
        
        t3 = F.Multiply(A_map[i+2][i],field_pow(x,E_map[i]))
        t3 = field_pow(t3,E_map[i+2])
        t3 = F.Multiply(t3,A_map[i+5][i+2])
        
        t4 = F.Multiply(A_map[i+3][i],field_pow(x,E_map[i]))
        t4 = field_pow(t4,E_map[i+3])
        t4 = F.Multiply(t4,A_map[i+5][i+3])
        
        t5 = F.Multiply(A_map[i+4][i],field_pow(x,E_map[i]))
        t5 = field_pow(t5,E_map[i+4])
        t5 = F.Multiply(t5,A_map[i+5][i+4])
        
        t6 = F.Multiply(aip5i,field_pow(x,E_map[i]))
        t6 = field_pow(t6,E_map[i+5])
        t6 = F.Multiply(t6,A_map[i+5][i+5])
        
        t = F.Add(t1,t2)
        t = F.Add(t,t3)
        t = F.Add(t,t4)
        t = F.Add(t,t5)
        t = F.Add(t,t6)
        
        t = field_pow(t,E_map[i+5])
        if(t==outval2):
            tuples2.append(aip5i)
            
    tuples3 = list(set(tuples) & set(tuples2))
    print(tuples3)
    A_map[i+5][i] = tuples3[0]

[54]
[30]
[9]


In [488]:
print(A_map)

[[  0   0   0   0   0   0   0   0   0]
 [  0 100   0   0   0   0   0   0   0]
 [  0 122  56   0   0   0   0   0   0]
 [  0   6 121  40   0   0   0   0   0]
 [  0  10  97  77  50   0   0   0   0]
 [  0  58  14  78  10  16   0   0   0]
 [  0   9  76 114 116  92  87   0   0]
 [  0   0  30  98  92 104  44  14   0]
 [  0   0   0  54  58 113  17  37 103]]


In [489]:
for ind in range(1,3):
    j=7
    i=3-ind
    outval = bin_to_dec(char_to_bin(string[i][1][2*(i+5):2*(i+6)]))
    x=2
    tuples = []
    for aip6i in range(0,128):
        t1 = F.Multiply(A_map[i][i],field_pow(x,E_map[i]))
        t1 = field_pow(t1,E_map[i])
        t1 = F.Multiply(t1,aip6i)
        
        t2 = F.Multiply(A_map[i+1][i],field_pow(x,E_map[i]))
        t2 = field_pow(t2,E_map[i+1])
        t2 = F.Multiply(t2,A_map[i+6][i+1])
        
        t3 = F.Multiply(A_map[i+2][i],field_pow(x,E_map[i]))
        t3 = field_pow(t3,E_map[i+2])
        t3 = F.Multiply(t3,A_map[i+6][i+2])
        
        t4 = F.Multiply(A_map[i+3][i],field_pow(x,E_map[i]))
        t4 = field_pow(t4,E_map[i+3])
        t4 = F.Multiply(t4,A_map[i+6][i+3])
        
        t5 = F.Multiply(A_map[i+4][i],field_pow(x,E_map[i]))
        t5 = field_pow(t5,E_map[i+4])
        t5 = F.Multiply(t5,A_map[i+6][i+4])
        
        t6 = F.Multiply(A_map[i+5][i],field_pow(x,E_map[i]))
        t6 = field_pow(t6,E_map[i+5])
        t6 = F.Multiply(t6,A_map[i+6][i+5])
        
        t7 = F.Multiply(aip6i,field_pow(x,E_map[i]))
        t7 = field_pow(t7,E_map[i+6])
        t7 = F.Multiply(t7,A_map[i+6][i+6])
        
        t = F.Add(t1,t2)
        t = F.Add(t,t3)
        t = F.Add(t,t4)
        t = F.Add(t,t5)
        t = F.Add(t,t6)
        t = F.Add(t,t7)
        
        t = field_pow(t,E_map[i+6])
        if(t==outval):
            tuples.append(aip6i)
            
    outval2 = bin_to_dec(char_to_bin(string[i][2][2*(i+5):2*(i+6)]))
    x=3
    tuples2 = []
    for aip6i in range(0,128):
        t1 = F.Multiply(A_map[i][i],field_pow(x,E_map[i]))
        t1 = field_pow(t1,E_map[i])
        t1 = F.Multiply(t1,aip6i)
        
        t2 = F.Multiply(A_map[i+1][i],field_pow(x,E_map[i]))
        t2 = field_pow(t2,E_map[i+1])
        t2 = F.Multiply(t2,A_map[i+6][i+1])
        
        t3 = F.Multiply(A_map[i+2][i],field_pow(x,E_map[i]))
        t3 = field_pow(t3,E_map[i+2])
        t3 = F.Multiply(t3,A_map[i+6][i+2])
        
        t4 = F.Multiply(A_map[i+3][i],field_pow(x,E_map[i]))
        t4 = field_pow(t4,E_map[i+3])
        t4 = F.Multiply(t4,A_map[i+6][i+3])
        
        t5 = F.Multiply(A_map[i+4][i],field_pow(x,E_map[i]))
        t5 = field_pow(t5,E_map[i+4])
        t5 = F.Multiply(t5,A_map[i+6][i+4])
        
        t6 = F.Multiply(A_map[i+5][i],field_pow(x,E_map[i]))
        t6 = field_pow(t6,E_map[i+5])
        t6 = F.Multiply(t6,A_map[i+6][i+5])
        
        t7 = F.Multiply(aip6i,field_pow(x,E_map[i]))
        t7 = field_pow(t7,E_map[i+6])
        t7 = F.Multiply(t7,A_map[i+6][i+6])
        
        t = F.Add(t1,t2)
        t = F.Add(t,t3)
        t = F.Add(t,t4)
        t = F.Add(t,t5)
        t = F.Add(t,t6)
        t = F.Add(t,t7)
        
        t = field_pow(t,E_map[i+6])
        if(t==outval2):
            tuples2.append(aip6i)
    
    tuples3 = list(set(tuples) & set(tuples2))
    print(tuples3)
    A_map[i+6][i] = tuples3[0]

[91]
[104]


In [490]:
print(A_map)

[[  0   0   0   0   0   0   0   0   0]
 [  0 100   0   0   0   0   0   0   0]
 [  0 122  56   0   0   0   0   0   0]
 [  0   6 121  40   0   0   0   0   0]
 [  0  10  97  77  50   0   0   0   0]
 [  0  58  14  78  10  16   0   0   0]
 [  0   9  76 114 116  92  87   0   0]
 [  0 104  30  98  92 104  44  14   0]
 [  0   0  91  54  58 113  17  37 103]]


In [491]:
for ind in range(1,2):
    j=7
    i=2-ind
    outval = bin_to_dec(char_to_bin(string[i][1][2*(i+6):2*(i+7)]))
    tuples = []
    x=2
    for aip7i in range(0,128):
        t1 = F.Multiply(A_map[i][i],field_pow(x,E_map[i]))
        t1 = field_pow(t1,E_map[i])
        t1 = F.Multiply(t1,aip7i)
        
        t2 = F.Multiply(A_map[i+1][i],field_pow(x,E_map[i]))
        t2 = field_pow(t2,E_map[i+1])
        t2 = F.Multiply(t2,A_map[i+7][i+1])
        
        t3 = F.Multiply(A_map[i+2][i],field_pow(x,E_map[i]))
        t3 = field_pow(t3,E_map[i+2])
        t3 = F.Multiply(t3,A_map[i+7][i+2])
        
        t4 = F.Multiply(A_map[i+3][i],field_pow(x,E_map[i]))
        t4 = field_pow(t4,E_map[i+3])
        t4 = F.Multiply(t4,A_map[i+7][i+3])
        
        t5 = F.Multiply(A_map[i+4][i],field_pow(x,E_map[i]))
        t5 = field_pow(t5,E_map[i+4])
        t5 = F.Multiply(t5,A_map[i+7][i+4])
        
        t6 = F.Multiply(A_map[i+5][i],field_pow(x,E_map[i]))
        t6 = field_pow(t6,E_map[i+5])
        t6 = F.Multiply(t6,A_map[i+7][i+5])
        
        t7 = F.Multiply(A_map[i+6][i],field_pow(x,E_map[i]))
        t7 = field_pow(t7,E_map[i+6])
        t7 = F.Multiply(t7,A_map[i+7][i+6])
        
        t8 = F.Multiply(aip7i,field_pow(x,E_map[i]))
        t8 = field_pow(t8,E_map[i+7])
        t8 = F.Multiply(t8,A_map[i+7][i+7])
        
        t = F.Add(t1,t2)
        t = F.Add(t,t3)
        t = F.Add(t,t4)
        t = F.Add(t,t5)
        t = F.Add(t,t6)
        t = F.Add(t,t7)
        t = F.Add(t,t8)
        
        t = field_pow(t,E_map[i+7])
        if(t==outval):
            tuples.append(aip7i)
            
    outval2 = bin_to_dec(char_to_bin(string[i][2][2*(i+6):2*(i+7)]))
    tuples2 = []
    x=3
    for aip7i in range(0,128):
        t1 = F.Multiply(A_map[i][i],field_pow(x,E_map[i]))
        t1 = field_pow(t1,E_map[i])
        t1 = F.Multiply(t1,aip7i)
        
        t2 = F.Multiply(A_map[i+1][i],field_pow(x,E_map[i]))
        t2 = field_pow(t2,E_map[i+1])
        t2 = F.Multiply(t2,A_map[i+7][i+1])
        
        t3 = F.Multiply(A_map[i+2][i],field_pow(x,E_map[i]))
        t3 = field_pow(t3,E_map[i+2])
        t3 = F.Multiply(t3,A_map[i+7][i+2])
        
        t4 = F.Multiply(A_map[i+3][i],field_pow(x,E_map[i]))
        t4 = field_pow(t4,E_map[i+3])
        t4 = F.Multiply(t4,A_map[i+7][i+3])
        
        t5 = F.Multiply(A_map[i+4][i],field_pow(x,E_map[i]))
        t5 = field_pow(t5,E_map[i+4])
        t5 = F.Multiply(t5,A_map[i+7][i+4])
        
        t6 = F.Multiply(A_map[i+5][i],field_pow(x,E_map[i]))
        t6 = field_pow(t6,E_map[i+5])
        t6 = F.Multiply(t6,A_map[i+7][i+5])
        
        t7 = F.Multiply(A_map[i+6][i],field_pow(x,E_map[i]))
        t7 = field_pow(t7,E_map[i+6])
        t7 = F.Multiply(t7,A_map[i+7][i+6])
        
        t8 = F.Multiply(aip7i,field_pow(x,E_map[i]))
        t8 = field_pow(t8,E_map[i+7])
        t8 = F.Multiply(t8,A_map[i+7][i+7])
        
        t = F.Add(t1,t2)
        t = F.Add(t,t3)
        t = F.Add(t,t4)
        t = F.Add(t,t5)
        t = F.Add(t,t6)
        t = F.Add(t,t7)
        t = F.Add(t,t8)
        
        t = field_pow(t,E_map[i+7])
        if(t==outval2):
            tuples2.append(aip7i)
            
    tuples3 = list(set(tuples) & set(tuples2))
    print(tuples3)
    A_map[i+7][i] = tuples3[0]

[13]


In [492]:
print(A_map,E_map)

[[  0   0   0   0   0   0   0   0   0]
 [  0 100   0   0   0   0   0   0   0]
 [  0 122  56   0   0   0   0   0   0]
 [  0   6 121  40   0   0   0   0   0]
 [  0  10  97  77  50   0   0   0   0]
 [  0  58  14  78  10  16   0   0   0]
 [  0   9  76 114 116  92  87   0   0]
 [  0 104  30  98  92 104  44  14   0]
 [  0  13  91  54  58 113  17  37 103]] [  0  85  52  38  72 116  38  66  50]


In [520]:
#############################
#    FINDING THE PLAIN-TEXT  ######
#############################

In [626]:
import urllib3
import urllib3.request
import requests
import json

In [648]:
password = "03de04de2867bb235d1026755622319d"
teamname = "codemeisters"
api_url = "https://172.27.26.181:9996/eaeae"
hdr = { "Accept": "/", "Accept-Encoding": "gzip, deflate, br", "Accept-Language": "en-US,en-IN;q=0.9,en-GB;q=0.8,en;q=0.7", "Connection": "keep-alive", "Content-Length": "85", "Content-Type": "text/html; charset=utf-8", "Host": "172.27.26.181:9996", "Origin": "https://172.27.26.181:9996", "Referer": "https://172.27.26.181:9996/game/caves.swf", "Sec-Fetch-Mode": "no-cors", "Sec-Fetch-Site": "same-origin", "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36", "X-Requested-With": "ShockwaveFlash/32.0.0.330" }

def encoder(text):
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
    d1 = {"password": password ,"teamname": teamname, "plaintext": text}
    x = requests.post(url=api_url, data = json.dumps(d1),headers=hdr,verify=False)
    ciph = x.json()['ciphertext']
    return ciph

In [641]:
pass1 = 'ktirlqhtlqijmmhq'
pass2 = 'mgkplijngrluiqlq'
plain1 = ['','','','','','','','']
plain2 = ['','','','','','','','']
encoder('fgh')

'fogmhjknilhufpmq'

In [642]:
for i in all_bytes_text:
    input_text = i+'ffffffffffffff'
    cipher_text = encoder(input_text)
    #print(cipher_text)
    if(cipher_text[0:2]==pass1[0:2]):
        print(input_text)

lhffffffffffffff


In [643]:
plain1[0]='lh'
for i in all_bytes_text:
    input_text = plain1[0] + i + 'ffffffffffff'
    cipher_text = encoder(input_text)
    if(cipher_text[2:4]==pass1[2:4]):
        print(input_text)

lhlgffffffffffff


In [644]:
plain1[1]='lg'
for i in all_bytes_text:
    input_text = plain1[0] + plain1[1] + i + 'ffffffffff'
    cipher_text = encoder(input_text)
    if(cipher_text[4:6]==pass1[4:6]):
        print(input_text)

lhlgmjffffffffff


In [645]:
plain1[2]='mj'
for i in all_bytes_text:
    input_text = plain1[0] + plain1[1] + plain1[2] + i + 'ffffffff'
    cipher_text = encoder(input_text)
    if(cipher_text[6:8]==pass1[6:8]):
        print(input_text)

lhlgmjmkffffffff


In [646]:
plain1[3]='mk'
for i in all_bytes_text:
    input_text = plain1[0] + plain1[1] + plain1[2] + plain1[3] + i + 'ffffff'
    cipher_text = encoder(input_text)
    if(cipher_text[8:10]==pass1[8:10]):
        print(input_text)

lhlgmjmkmgffffff


In [649]:
plain1[4] = 'mg'
for i in all_bytes_text:
    input_text = plain1[0] + plain1[1] + plain1[2] + plain1[3] + plain1[4] + i + 'ffff'
    cipher_text = encoder(input_text)
    if(cipher_text[10:12]==pass1[10:12]):
        print(input_text)

lhlgmjmkmglqffff


In [650]:
plain1[5] = 'lq'
for i in all_bytes_text:
    input_text = plain1[0] + plain1[1] + plain1[2] + plain1[3] + plain1[4] + plain1[5] + i + 'ff'
    cipher_text = encoder(input_text)
    if(cipher_text[12:14]==pass1[12:14]):
        print(input_text)

lhlgmjmkmglqloff


In [651]:
plain1[6]='lo'
for i in all_bytes_text:
    input_text = plain1[0] + plain1[1] + plain1[2] + plain1[3] + plain1[4] + plain1[5] + plain1[6] + i 
    cipher_text = encoder(input_text)
    if(cipher_text[14:16]==pass1[14:16]):
        print(input_text)

lhlgmjmkmglqlomp


In [652]:
plain1[7] = 'mp'

'ffgffrlljmffgphf'

In [655]:
for i in all_bytes_text:
    input_text = i+'ffffffffffffff'
    cipher_text = encoder(input_text)
    #print(cipher_text)
    if(cipher_text[0:2]==pass2[0:2]):
        plain2[0]=i
        print(plain2[0])

for i in all_bytes_text:
    input_text = plain2[0] + i + 'ffffffffffff'
    cipher_text = encoder(input_text)
    if(cipher_text[2:4]==pass2[2:4]):
        plain2[1]=i
        print(plain2[1])
        
for i in all_bytes_text:
    input_text = plain2[0] + plain2[1] + i + 'ffffffffff'
    cipher_text = encoder(input_text)
    if(cipher_text[4:6]==pass2[4:6]):
        plain2[2]=i
        print(plain2[2])
        
for i in all_bytes_text:
    input_text = plain2[0] + plain2[1] + plain2[2] + i + 'ffffffff'
    cipher_text = encoder(input_text)
    if(cipher_text[6:8]==pass2[6:8]):
        plain2[3]=i
        print(plain2[3])
        
for i in all_bytes_text:
    input_text = plain2[0] + plain2[1] + plain2[2] + plain2[3] + i + 'ffffff'
    cipher_text = encoder(input_text)
    if(cipher_text[8:10]==pass2[8:10]):
        plain2[4]=i
        print(plain2[4])
        
for i in all_bytes_text:
    input_text = plain2[0] + plain2[1] + plain2[2] + plain2[3] + plain2[4] + i + 'ffff'
    cipher_text = encoder(input_text)
    if(cipher_text[10:12]==pass2[10:12]):
        plain2[5]=i
        print(plain2[5])
        
for i in all_bytes_text:
    input_text = plain2[0] + plain2[1] + plain2[2] + plain2[3] + plain2[4] + plain2[5] + i + 'ff'
    cipher_text = encoder(input_text)
    if(cipher_text[12:14]==pass2[12:14]):
        plain2[6]=i
        print(plain2[6])
        
for i in all_bytes_text:
    input_text = plain2[0] + plain2[1] + plain2[2] + plain2[3] + plain2[4] + plain2[5] + plain2[6] + i 
    cipher_text = encoder(input_text)
    if(cipher_text[14:16]==pass2[14:16]):
        plain2[7]=i
        print(plain2[7])

mo
lt
mg
li
lq
lm
lg
mh


In [656]:
plain_text1 = ''
plain_text2 = ''
for i in range(0,8):
    plain_text1 = plain_text1 + plain1[i]
    plain_text2 = plain_text2 + plain2[i]
    
print(plain_text1,plain_text2)

lhlgmjmkmglqlomp moltmglilqlmlgmh


In [658]:
ans = ''
for i in plain1:
    ascii_val = bin_to_dec(char_to_bin(i))
    ans = ans+ chr(ascii_val)
    
for i in plain2:
    ascii_val = bin_to_dec(char_to_bin(i))
    ans = ans+ chr(ascii_val)
    
print(ans)

batuqkizynqckgar
